name: Check Links

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.0.2
        with:
          args: '--verbose --no-progress .'
          fail: true
